spring:
  application:
    name: activemq-consumer
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
    user: ${ACTIVEMQ_USER:admin}
    password: ${ACTIVEMQ_PASSWORD:admin}
  jms:
    pub-sub-domain: true

server:
  port: 8081

app:
  listener:
    worker-concurrency: 3-3
    fail-seq-multiple: 0
  topics:
    virtual-orders: VirtualTopic.orders
  queues:
    worker-a: Consumer.workers.VirtualTopic.orders  # pattern Consumer.<group>.VirtualTopic.<topicName>
    worker-b: Consumer.workers.VirtualTopic.orders  # pattern Consumer.<group>.VirtualTopic.<topicName>
    quote: orders.quote.queue
  subscriptions:
    orders-durable: orders-durable-sub

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
